ServerRoot "/usr/local/apache2"
Listen 8081
ServerName recommendations-v1
PidFile "/tmp/httpd.pid"
ErrorLog /proc/self/fd/2
LogLevel warn

LoadModule mpm_event_module modules/mod_mpm_event.so
LoadModule authn_core_module modules/mod_authn_core.so
LoadModule authz_core_module modules/mod_authz_core.so
LoadModule access_compat_module modules/mod_access_compat.so
LoadModule alias_module modules/mod_alias.so
LoadModule dir_module modules/mod_dir.so
LoadModule log_config_module modules/mod_log_config.so
LoadModule mime_module modules/mod_mime.so
LoadModule rewrite_module modules/mod_rewrite.so
LoadModule unixd_module modules/mod_unixd.so

User daemon
Group daemon

TypesConfig conf/mime.types
DocumentRoot "/usr/local/apache2/htdocs"
Define APACHE_HTDOCS_ROOT /usr/local/apache2/htdocs

<Directory "/usr/local/apache2/htdocs">
    AllowOverride None
    Require all granted
</Directory>

LogFormat "%h %l %u %t \"%r\" %>s %b" common
CustomLog /proc/self/fd/1 common

Include conf/shared/recommendations-v1-vhost.conf
