FROM eclipse-temurin:17@sha256:b624cb9175b71aaeb654dd9def666035332d5abf70318537c1a46e61564dbecd AS javabuilder

# Install tar and gzip to extract the Maven binaries
RUN apt install -y tar gzip

# Install Maven
ARG USER_HOME_DIR="/cache"

# Set the working directory to /home/app
WORKDIR /build

# Copy the source code into the image for building
COPY internal/test/integration/components/javakafka/.mvn .mvn/
COPY internal/test/integration/components/javakafka/mvnw mvnw
COPY internal/test/integration/components/javatestserver/src src/
COPY internal/test/integration/components/javatestserver/pom.xml pom.xml

RUN java -version
RUN ./mvnw -version

# Build
RUN ./mvnw clean package

# The App Image
FROM eclipse-temurin:17.0.18_8-jre@sha256:ff692acf872589e72ca71b416b3e949ec19f35ebe8abb5365d2f31bce298e762

EXPOSE 8085

# Copy the native executable into the containers
COPY --from=javabuilder /build/target/greeting-service-1.2.0.jar .
CMD [ "java", "-jar", "/greeting-service-1.2.0.jar" ]