# TODO: if zizmor doesn't pass, don't run any other action
name: GitHub Actions Security Analysis with zizmor 🌈

on:
  push:
    branches: ["main", "release-*"]
  pull_request:
    branches: ["**"]

concurrency:
  group: gh-actions-security-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  zizmor:
    name: zizmor latest via PyPI
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@cec208311dfd045dd5311c1add060b2062131d57 # v8.0.0
        with:
          enable-cache: false

      - name: Run zizmor 🌈
        run: |
          uv venv .venv
          uv pip install --require-hashes -r .github/zizmor-requirements.txt
          .venv/bin/zizmor --format=github .github/
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
